### ISSUE TITLE
큰일났따!!!

### ISSUE THREAD

**Issue by jsk41755** [Bangseungjae/testing-tool#6]
.　|＿＿＿
　|　　 　＼　
　|　 ,ノ　   ＼
　|　（ ●）ｕ ＼
　|人__）　　　|
　|⌒´　　　 ／    큰일났다
(⌒ー─’　 　）    이 사람은 보통이 아니야!

**Comment by Bangseungjae** [comment]
What's?

**Comment by Bangseungjae** [comment]
g
